#!/usr/bin/env python3

from __future__ import annotations

import html
import json
import re
import subprocess
import sys
from pathlib import Path


def usage() -> None:
    print(
        "Usage: build_report_html.py <input-markdown> <output-html>",
        file=sys.stderr,
    )
    raise SystemExit(1)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def section_lines(markdown: str, heading: str) -> list[str]:
    lines = markdown.splitlines()
    capture = False
    collected: list[str] = []
    needle = f"## {heading}"
    for line in lines:
      if line.startswith("## ") and capture:
        break
      if line == needle:
        capture = True
        continue
      if capture:
        collected.append(line)
    return collected


def parse_markdown_table(lines: list[str]) -> list[dict[str, str]]:
    table_lines = [line.strip() for line in lines if line.strip().startswith("|")]
    if len(table_lines) < 2:
        return []

    header = [cell.strip() for cell in table_lines[0].strip("|").split("|")]
    rows: list[dict[str, str]] = []
    for line in table_lines[2:]:
        values = [cell.strip() for cell in line.strip("|").split("|")]
        if len(values) != len(header):
            continue
        rows.append(dict(zip(header, values)))
    return rows


def clean_markdown_text(value: str) -> str:
    cleaned = value.strip()
    cleaned = re.sub(r"`([^`]*)`", r"\1", cleaned)
    cleaned = re.sub(r"\*\*([^*]+)\*\*", r"\1", cleaned)
    cleaned = re.sub(r"\*([^*]+)\*", r"\1", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned.strip()


def first_paragraph(lines: list[str]) -> str:
    paragraph: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if paragraph:
                break
            continue
        if stripped.startswith("|") or stripped.startswith("- ") or stripped.startswith("1. "):
            if paragraph:
                break
            continue
        paragraph.append(stripped)
    return " ".join(paragraph)


def extract_title(markdown: str) -> str:
    for line in markdown.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return "Web3 SDL Report"


def markdown_to_html_fragment(input_path: Path) -> str:
    result = subprocess.run(
        [
            "pandoc",
            str(input_path),
            "--from=markdown",
            "--to=html5",
            "--section-divs",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def render_cover(meta: dict[str, object]) -> str:
    snapshot = meta.get("snapshot", {})
    assert isinstance(snapshot, dict)
    summary = html.escape(str(meta.get("summary", "")))

    cards = [
        ("Repository", snapshot.get("Repository", "Unknown")),
        ("Workflow", snapshot.get("Workflow", "Unknown")),
        ("Commit Range", snapshot.get("Commit Range", "Unknown")),
        ("Outcome", snapshot.get("Primary Outcome", "Unknown")),
    ]

    card_html = []
    for label, value in cards:
        card_html.append(
            "<div class=\"cover-card\">"
            f"<span class=\"cover-card-label\">{html.escape(str(label))}</span>"
            f"<div class=\"cover-card-value\">{html.escape(str(value))}</div>"
            "</div>"
        )

    return (
        "<section id=\"cover-page\" class=\"cover-page\">"
        "<div>"
        "<div class=\"cover-kicker\">Security Review Artifact</div>"
        f"<h1 class=\"cover-title\">{html.escape(str(meta.get('title', 'Web3 SDL Report')))}</h1>"
        f"<p class=\"cover-subtitle\">{summary}</p>"
        f"<div class=\"cover-summary\">Review date: {html.escape(str(snapshot.get('Review Date', 'Unknown')))}</div>"
        f"<div class=\"cover-grid\">{''.join(card_html)}</div>"
        "<div class=\"cover-badges\"></div>"
        "</div>"
        "<div class=\"report-footer-note\">Generated by web3-sdl-workflows browser renderer.</div>"
        "</section>"
    )


def main() -> None:
    if len(sys.argv) != 3:
        usage()

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    if not input_path.is_file():
        print(f"Input markdown file not found: {input_path}", file=sys.stderr)
        raise SystemExit(1)

    script_dir = Path(__file__).resolve().parent
    skill_root = script_dir.parent
    css_path = skill_root / "assets" / "templates" / "report-theme.css"
    js_path = skill_root / "assets" / "templates" / "report-enhancer.js"

    markdown = read_text(input_path)
    title = extract_title(markdown)
    snapshot_rows = parse_markdown_table(section_lines(markdown, "Engagement Snapshot"))
    summary_rows = parse_markdown_table(section_lines(markdown, "Executive Summary"))
    snapshot = {row.get("Field", ""): row.get("Value", "") for row in snapshot_rows}
    severity_counts = [
        {
            "label": clean_markdown_text(row.get("Severity", "")),
            "count": clean_markdown_text(row.get("Count", "")),
        }
        for row in summary_rows
        if row.get("Severity")
    ]
    summary = first_paragraph(section_lines(markdown, "Executive Summary"))
    snapshot = {
        clean_markdown_text(key): clean_markdown_text(value)
        for key, value in snapshot.items()
    }

    meta = {
        "title": title,
        "snapshot": snapshot,
        "severity_counts": severity_counts,
        "summary": summary,
    }

    fragment = markdown_to_html_fragment(input_path)
    css = read_text(css_path)
    enhancer = read_text(js_path)

    html_output = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{html.escape(title)}</title>
  <style>{css}</style>
  <script>window.__REPORT_META__ = {json.dumps(meta)};</script>
</head>
<body>
  {render_cover(meta)}
  <nav id="generated-toc" class="toc-page"></nav>
  <main id="report-content">
    {fragment}
  </main>
  <script>{enhancer}</script>
</body>
</html>
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_output, encoding="utf-8")


if __name__ == "__main__":
    main()
